{
  "data": {
    "id": "ember-1.4.0-Ember.Test.QUnitAdapter",
    "type": "class",
    "attributes": {
      "name": "Ember.Test.QUnitAdapter",
      "shortname": "Ember.Test.QUnitAdapter",
      "classitems": [],
      "plugins": [],
      "extensions": [],
      "plugin_for": [],
      "extension_for": [],
      "module": "ember",
      "submodule": "ember-testing",
      "namespace": "Ember.Test",
      "file": "../packages/ember-testing/lib/adapters.js",
      "line": 59,
      "description": "This class implements the methods defined by Ember.Test.Adapter for the\nQUnit testing framework.",
      "extends": "Ember.Test.Adapter",
      "methods": [
        {
          "file": "../packages/ember-testing/lib/adapters.js",
          "line": 18,
          "description": "This callback will be called whenever an async operation is about to start.\n\nOverride this to call your framework's methods that handle async\noperations.",
          "access": "public",
          "tagname": "",
          "itemtype": "method",
          "name": "asyncStart",
          "class": "Ember.Test.QUnitAdapter",
          "module": "ember",
          "submodule": "ember-testing",
          "namespace": "Ember.Test",
          "inherited": true,
          "inheritedFrom": "Ember.Test.Adapter"
        },
        {
          "file": "../packages/ember-testing/lib/adapters.js",
          "line": 29,
          "description": "This callback will be called whenever an async operation has completed.",
          "access": "public",
          "tagname": "",
          "itemtype": "method",
          "name": "asyncEnd",
          "class": "Ember.Test.QUnitAdapter",
          "module": "ember",
          "submodule": "ember-testing",
          "namespace": "Ember.Test",
          "inherited": true,
          "inheritedFrom": "Ember.Test.Adapter"
        },
        {
          "file": "../packages/ember-testing/lib/adapters.js",
          "line": 37,
          "description": "Override this method with your testing framework's false assertion.\nThis function is called whenever an exception occurs causing the testing\npromise to fail.\n\nQUnit example:\n\n```javascript\n  exception: function(error) {\n    ok(false, error);\n  };\n```",
          "access": "public",
          "tagname": "",
          "itemtype": "method",
          "name": "exception",
          "params": [
            {
              "name": "error",
              "description": "The exception to be raised.",
              "type": "String"
            }
          ],
          "class": "Ember.Test.QUnitAdapter",
          "module": "ember",
          "submodule": "ember-testing",
          "namespace": "Ember.Test",
          "inherited": true,
          "inheritedFrom": "Ember.Test.Adapter"
        }
      ],
      "events": [],
      "properties": []
    },
    "relationships": {
      "parent-class": {
        "data": {
          "id": "ember-1.4.0-Ember.Test.Adapter",
          "type": "class"
        }
      },
      "descendants": {
        "data": []
      },
      "module": {
        "data": {
          "id": "ember-1.4.0-ember",
          "type": "module"
        }
      },
      "project-version": {
        "data": {
          "id": "ember-1.4.0",
          "type": "project-version"
        }
      }
    }
  }
}